// Code generated by MockGen. DO NOT EDIT.
// Source: minio.go

// Package mock_infrastructure is a generated GoMock package.
package mock_infrastructure

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	minio "github.com/minio/minio-go/v7"
)

// MockIMinioClient is a mock of IMinioClient interface.
type MockIMinioClient struct {
	ctrl     *gomock.Controller
	recorder *MockIMinioClientMockRecorder
}

// MockIMinioClientMockRecorder is the mock recorder for MockIMinioClient.
type MockIMinioClientMockRecorder struct {
	mock *MockIMinioClient
}

// NewMockIMinioClient creates a new mock instance.
func NewMockIMinioClient(ctrl *gomock.Controller) *MockIMinioClient {
	mock := &MockIMinioClient{ctrl: ctrl}
	mock.recorder = &MockIMinioClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMinioClient) EXPECT() *MockIMinioClientMockRecorder {
	return m.recorder
}

// GetObject mocks base method.
func (m *MockIMinioClient) GetObject(ctx context.Context, objectName string, opts minio.GetObjectOptions) (*minio.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, objectName, opts)
	ret0, _ := ret[0].(*minio.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockIMinioClientMockRecorder) GetObject(ctx, objectName, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockIMinioClient)(nil).GetObject), ctx, objectName, opts)
}
