root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/bin/reconciliation-service ./cmd/server"
bin = "tmp/bin/reconciliation-service"
full_bin = "env LOG_LEVEL=debug ./tmp/bin/reconciliation-service start"
delay = 1000
log = "air_errors.log"
include_ext = ["go", "yaml", "json"]
exclude_dir = ["tmp"]
stop_on_error = true

[log]
time = true

[misc]
clean_on_exit = true